package com.ibm.health.common.vaccination.app

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.webkit.WebView
import com.ibm.health.common.navigation.android.FragmentNav
import kotlinx.parcelize.Parcelize

@Parcelize
public class OpenSourceLicenseFragmentNav : FragmentNav(OpenSourceLicenseFragment::class)

/**
 * Displays open source licenses for all app dependencies. The licenses are displayed in a webview, the html is
 * generated by the plugin https://github.com/jaredsburrows/gradle-license-plugin.
 */
public class OpenSourceLicenseFragment : BaseFragment() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        // This is just a provisional implementation.
        val webView = WebView(requireActivity())
        webView.loadUrl("file:///android_asset/open_source_licenses.html")
        return webView
    }
}
