name: Upload Android Vaccination App to Souce Labs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  download-image:
    runs-on: self-hosted
    
    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      
    steps:
      - name: download from nexus
        run: curl -X GET -u $NEXUS_USERNAME:$NEXUS_PASSWORD https://nexus.open-insurance-platform.com/#browse/browse:covpass-releases:com%2Fibm%2Fhealth%2Fde%2Frki%2Fcovpass%2Fapp-covpass-demo--debug%2F1.510.0%2Fapp-covpass-demo--debug-1.510.0.zip:~:text=Path-,com/ibm/health/de/rki/covpass/app%2Dcovpass%2Ddemo%2D%2Ddebug/1.510.0/app%2Dcovpass%2Ddemo%2D%2Ddebug%2D1.510.0.zip,-Content%20type -O
      - name: cleanup
        run: ls
    
  
  
  
  
  
  
  
 
